baseurl: /crox
permalink: /:categories/:title
excerpt_separator: "\n\n"
exclude:
  - Gruntfile.js
  - crox.sublime-project
  - package.json
  - readme.md
  - node_modules

title: Crox
url: https://thx.github.io/crox

gems:
  - jekyll-feed
  - jekyll-sitemap
